# Generated by Django 5.2.3 on 2025-06-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('dia', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('entrada', models.TimeField(blank=True, null=True)),
                ('inicio_intervalo', models.TimeField(blank=True, null=True)),
                ('fim_intervalo', models.TimeField(blank=True, null=True)),
                ('saida', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('folga', 'Folga'), ('atestado', 'Atestado')], default='normal', max_length=10)),
            ],
            options={
                'ordering': ['ano', 'mes', 'dia'],
                'unique_together': {('ano', 'mes', 'dia')},
            },
        ),
    ]
